// GENERATED by tool/figma/gen_glow.py from the background fits
// (tool/figma/bgfit.py). Do not edit by hand: refit and regenerate.
//
// One recipe per design PNG, named by its pack position (s8 = Small/8).
// The rms column is the fit error over the background pixels, in 8-bit
// levels. Metric names alias these in glow.dart's Glows.

import 'package:flutter/painting.dart';

import 'glow.dart';

abstract final class GlowRecipes {
  /// Small/2.png (164×218), fit rms 1.22.
  static const s2 = GlowRecipe(
    size: Size(164, 218),
    base: Color(0xFF007101),
    blobs: [
      GlowBlob(
        center: Offset(793.55, 610.17),
        radii: Size(384.19, 1096.63),
        rotation: 1.9323,
        softness: 0.1170,
        alpha: 1.0000,
        color: Color(0xFFC2CC78),
      ),
      GlowBlob(
        center: Offset(83.13, 111.60),
        radii: Size(97.96, 72.95),
        rotation: 0.0117,
        softness: 0.5038,
        alpha: 1.0000,
        color: Color(0xFF020005),
      ),
      GlowBlob(
        center: Offset(96.71, 169.88),
        radii: Size(18.25, 52.13),
        rotation: 1.2751,
        softness: 0.3637,
        alpha: 0.0379,
        color: Color(0xFFFFD99F),
      ),
      GlowBlob(
        center: Offset(172.81, 150.68),
        radii: Size(41.24, 138.86),
        rotation: 1.1777,
        softness: 0.1100,
        alpha: 0.1461,
        color: Color(0xFF1F4C14),
      ),
      GlowBlob(
        center: Offset(-264.13, 293.81),
        radii: Size(27.11, 263.74),
        rotation: 1.3975,
        softness: 0.7734,
        alpha: 1.0000,
        color: Color(0xFFFFDBA1),
      ),
    ],
  );

  /// Small/5.png (164×218), fit rms 0.38.
  static const s5 = GlowRecipe(
    size: Size(164, 218),
    base: Color(0xFF0A0002),
    blobs: [
      GlowBlob(
        center: Offset(-575.21, 539.31),
        radii: Size(167.96, 1096.63),
        rotation: 0.7599,
        softness: 0.2724,
        alpha: 1.0000,
        color: Color(0xFFD0FF61),
      ),
      GlowBlob(
        center: Offset(-238.15, 632.89),
        radii: Size(134.04, 554.26),
        rotation: 0.4806,
        softness: 0.1520,
        alpha: 0.5126,
        color: Color(0xFF72FF94),
      ),
      GlowBlob(
        center: Offset(1018.44, -585.81),
        radii: Size(154.80, 1096.63),
        rotation: -2.1904,
        softness: 0.0787,
        alpha: 0.2305,
        color: Color(0xFF73FF91),
      ),
      GlowBlob(
        center: Offset(382.68, 978.39),
        radii: Size(197.55, 1096.63),
        rotation: -0.3432,
        softness: 0.0920,
        alpha: 0.3794,
        color: Color(0xFF001014),
      ),
      GlowBlob(
        center: Offset(155.23, 208.22),
        radii: Size(65.70, 103.13),
        rotation: 0.1477,
        softness: 0.0875,
        alpha: 1.0000,
        color: Color(0xFF0A0A0A),
      ),
    ],
  );

  /// Small/6.png (164×218), fit rms 1.58.
  static const s6 = GlowRecipe(
    size: Size(164, 218),
    base: Color(0xFF080907),
    blobs: [
      GlowBlob(
        center: Offset(207.55, -688.30),
        radii: Size(81.21, 1096.63),
        rotation: 0.0015,
        softness: 0.1985,
        alpha: 0.8978,
        color: Color(0xFF573F73),
      ),
      GlowBlob(
        center: Offset(14.25, 207.26),
        radii: Size(29.08, 1096.63),
        rotation: -0.4093,
        softness: 0.8133,
        alpha: 0.3473,
        color: Color(0xFFFF56BB),
      ),
      GlowBlob(
        center: Offset(-156.28, 441.48),
        radii: Size(62.36, 1096.63),
        rotation: 0.9905,
        softness: 0.3843,
        alpha: 0.2559,
        color: Color(0xFFFF6EE5),
      ),
      GlowBlob(
        center: Offset(-5.52, -238.38),
        radii: Size(95.25, 300.85),
        rotation: -0.5440,
        softness: 0.1343,
        alpha: 0.2956,
        color: Color(0xFFAA87FF),
      ),
      GlowBlob(
        center: Offset(78.96, -458.49),
        radii: Size(131.34, 609.49),
        rotation: 0.2589,
        softness: 0.1364,
        alpha: 0.3775,
        color: Color(0xFFF27FFF),
      ),
    ],
  );

  /// Small/7.png (164×218), fit rms 0.95.
  static const s7 = GlowRecipe(
    size: Size(164, 218),
    base: Color(0xFF2D2D24),
    blobs: [
      GlowBlob(
        center: Offset(64.50, -12.37),
        radii: Size(7.36, 1096.63),
        rotation: 1.5664,
        softness: 6.1832,
        alpha: 1.0000,
        color: Color(0xFF24FF96),
      ),
      GlowBlob(
        center: Offset(-249.45, 218.00),
        radii: Size(16.13, 1096.63),
        rotation: -1.5718,
        softness: 3.4582,
        alpha: 1.0000,
        color: Color(0xFFFF345A),
      ),
      GlowBlob(
        center: Offset(246.09, -1128.47),
        radii: Size(223.98, 1096.63),
        rotation: 0.0072,
        softness: 0.0971,
        alpha: 1.0000,
        color: Color(0xFF70FFA9),
      ),
      GlowBlob(
        center: Offset(56.32, -1137.22),
        radii: Size(188.44, 1096.63),
        rotation: 0.1169,
        softness: 0.1298,
        alpha: 1.0000,
        color: Color(0xFF77FFAA),
      ),
      GlowBlob(
        center: Offset(81.78, 113.57),
        radii: Size(60.72, 50.00),
        rotation: 0.0118,
        softness: 0.4198,
        alpha: 0.8760,
        color: Color(0xFF000204),
      ),
    ],
  );

  /// Small/8.png (164×218), fit rms 1.40.
  static const s8 = GlowRecipe(
    size: Size(164, 218),
    base: Color(0xFF0A0908),
    blobs: [
      GlowBlob(
        center: Offset(164.05, 42.81),
        radii: Size(16.04, 1096.63),
        rotation: -0.1740,
        softness: 0.9406,
        alpha: 1.0000,
        color: Color(0xFF0A1E39),
      ),
      GlowBlob(
        center: Offset(-421.51, -120.79),
        radii: Size(58.12, 1096.63),
        rotation: 1.7242,
        softness: 0.3830,
        alpha: 0.2154,
        color: Color(0xFF0D72FF),
      ),
      GlowBlob(
        center: Offset(719.68, -330.84),
        radii: Size(3.74, 1096.63),
        rotation: 0.8205,
        softness: 7.3891,
        alpha: 0.4004,
        color: Color(0xFF0D72FF),
      ),
      GlowBlob(
        center: Offset(2.97, 27.08),
        radii: Size(17.81, 1096.63),
        rotation: 0.3100,
        softness: 0.9683,
        alpha: 0.2438,
        color: Color(0xFF0D72FF),
      ),
      GlowBlob(
        center: Offset(-290.29, -72.76),
        radii: Size(62.21, 1096.63),
        rotation: -0.7396,
        softness: 0.4000,
        alpha: 0.2884,
        color: Color(0xFF0D72FF),
      ),
    ],
  );

  /// Small/9.png (164×218), fit rms 0.22.
  static const s9 = GlowRecipe(
    size: Size(164, 218),
    base: Color(0xFF043326),
    blobs: [
      GlowBlob(
        center: Offset(81.98, 109.23),
        radii: Size(42.06, 41.69),
        rotation: -35.1573,
        softness: 0.1416,
        alpha: 1.0000,
        color: Color(0xFF050006),
      ),
      GlowBlob(
        center: Offset(82.08, 109.20),
        radii: Size(118.04, 112.64),
        rotation: -0.0010,
        softness: 0.1809,
        alpha: 0.3973,
        color: Color(0xFF0B0304),
      ),
      GlowBlob(
        center: Offset(82.06, 109.16),
        radii: Size(68.57, 65.51),
        rotation: 0.0031,
        softness: 0.3063,
        alpha: 0.9294,
        color: Color(0xFF0C0808),
      ),
      GlowBlob(
        center: Offset(82.09, 109.21),
        radii: Size(88.31, 84.43),
        rotation: 0.0099,
        softness: 0.0095,
        alpha: 0.1174,
        color: Color(0xFF001C17),
      ),
      GlowBlob(
        center: Offset(130.92, 115.27),
        radii: Size(5.13, 1.00),
        rotation: 1.7968,
        softness: 3.8971,
        alpha: 0.5108,
        color: Color(0xFF060E0C),
      ),
    ],
  );

  /// Small/17.png (164×164), fit rms 0.70.
  static const s17 = GlowRecipe(
    size: Size(164, 164),
    base: Color(0xFFA1326B),
    blobs: [
      GlowBlob(
        center: Offset(48.94, -18.87),
        radii: Size(1096.63, 10.71),
        rotation: -0.0010,
        softness: 2.8252,
        alpha: 1.0000,
        color: Color(0xFFFF4281),
      ),
      GlowBlob(
        center: Offset(-12.53, 365.58),
        radii: Size(1096.63, 246.01),
        rotation: -0.0187,
        softness: 0.3116,
        alpha: 1.0000,
        color: Color(0xFF5357FA),
      ),
      GlowBlob(
        center: Offset(82.52, 85.04),
        radii: Size(95.24, 55.40),
        rotation: 12.5719,
        softness: 0.4874,
        alpha: 1.0000,
        color: Color(0xFF000000),
      ),
      GlowBlob(
        center: Offset(847.27, 92.09),
        radii: Size(1096.63, 24.31),
        rotation: -6.3366,
        softness: 0.3940,
        alpha: 0.2545,
        color: Color(0xFF48265F),
      ),
      GlowBlob(
        center: Offset(-13.89, 340.41),
        radii: Size(336.29, 189.68),
        rotation: 2.7942,
        softness: 0.0433,
        alpha: 0.0501,
        color: Color(0xFF6758FF),
      ),
    ],
  );

  /// Medium/5.png (348×164), fit rms 0.53.
  static const m5 = GlowRecipe(
    size: Size(348, 164),
    base: Color(0xFF050029),
    blobs: [
      GlowBlob(
        center: Offset(34.62, 0.96),
        radii: Size(1096.63, 12.46),
        rotation: -0.0341,
        softness: 5.5689,
        alpha: 1.0000,
        color: Color(0xFF2D9EC5),
      ),
      GlowBlob(
        center: Offset(146.22, 1102.18),
        radii: Size(1096.63, 326.19),
        rotation: 1.2864,
        softness: 0.2092,
        alpha: 0.8249,
        color: Color(0xFF3CD8FF),
      ),
      GlowBlob(
        center: Offset(168.41, 182.81),
        radii: Size(147.50, 37.00),
        rotation: -0.0281,
        softness: 0.8105,
        alpha: 0.5206,
        color: Color(0xFF2B96BC),
      ),
      GlowBlob(
        center: Offset(260.64, 883.07),
        radii: Size(1096.63, 256.67),
        rotation: -1.2400,
        softness: 0.3862,
        alpha: 0.7572,
        color: Color(0xFF3DD8FF),
      ),
      GlowBlob(
        center: Offset(973.71, 100.04),
        radii: Size(1096.63, 23.43),
        rotation: -0.0299,
        softness: 0.6648,
        alpha: 0.2253,
        color: Color(0xFF1F658F),
      ),
    ],
  );

  /// Medium/7.png (348×164), fit rms 1.59.
  static const m7 = GlowRecipe(
    size: Size(348, 164),
    base: Color(0xFF3A6B40),
    blobs: [
      GlowBlob(
        center: Offset(158.75, -126.68),
        radii: Size(1096.63, 136.12),
        rotation: -0.2760,
        softness: 0.2669,
        alpha: 1.0000,
        color: Color(0xFF7DFFCE),
      ),
      GlowBlob(
        center: Offset(336.99, 49.94),
        radii: Size(113.72, 27.71),
        rotation: -0.2171,
        softness: 0.4408,
        alpha: 1.0000,
        color: Color(0xFF000000),
      ),
      GlowBlob(
        center: Offset(208.01, 1276.28),
        radii: Size(1096.63, 444.46),
        rotation: 1.3280,
        softness: 0.1712,
        alpha: 1.0000,
        color: Color(0xFFABFF00),
      ),
      GlowBlob(
        center: Offset(28.13, 283.56),
        radii: Size(466.40, 67.58),
        rotation: -0.3104,
        softness: 0.3837,
        alpha: 1.0000,
        color: Color(0xFFA7FF14),
      ),
      GlowBlob(
        center: Offset(249.02, 71.61),
        radii: Size(161.77, 42.55),
        rotation: -0.2292,
        softness: 1.0657,
        alpha: 0.8896,
        color: Color(0xFF000000),
      ),
      GlowBlob(
        center: Offset(-889.67, 504.19),
        radii: Size(1096.63, 132.36),
        rotation: -0.2803,
        softness: 0.1423,
        alpha: 1.0000,
        color: Color(0xFF629100),
      ),
    ],
  );

  /// Medium/8.png (348×164), fit rms 0.32.
  static const m8 = GlowRecipe(
    size: Size(348, 164),
    base: Color(0xFF1D1B4A),
    blobs: [
      GlowBlob(
        center: Offset(15.60, 155.46),
        radii: Size(142.65, 40.16),
        rotation: -0.4617,
        softness: 0.7759,
        alpha: 1.0000,
        color: Color(0xFF7F3DAF),
      ),
      GlowBlob(
        center: Offset(20.69, 210.83),
        radii: Size(254.39, 47.49),
        rotation: -0.4925,
        softness: 0.3856,
        alpha: 0.3615,
        color: Color(0xFF360009),
      ),
      GlowBlob(
        center: Offset(223.23, 229.63),
        radii: Size(1096.63, 39.43),
        rotation: -0.8595,
        softness: 0.2169,
        alpha: 1.0000,
        color: Color(0xFF1E1B4B),
      ),
      GlowBlob(
        center: Offset(-747.41, 495.67),
        radii: Size(1096.63, 88.27),
        rotation: -0.4690,
        softness: 0.1018,
        alpha: 0.1124,
        color: Color(0xFFD262FF),
      ),
      GlowBlob(
        center: Offset(161.42, 80.21),
        radii: Size(133.52, 31.20),
        rotation: -0.4329,
        softness: 0.4205,
        alpha: 0.3069,
        color: Color(0xFF361741),
      ),
      GlowBlob(
        center: Offset(-173.16, 223.56),
        radii: Size(290.40, 14.83),
        rotation: -0.5084,
        softness: 2.3348,
        alpha: 0.2649,
        color: Color(0xFF000104),
      ),
    ],
  );

  /// Medium/10.png (348×164), fit rms 0.82.
  static const m10 = GlowRecipe(
    size: Size(348, 164),
    base: Color(0xFF170008),
    blobs: [
      GlowBlob(
        center: Offset(-1175.81, -4.85),
        radii: Size(1096.63, 71.12),
        rotation: -0.0791,
        softness: 1.7257,
        alpha: 1.0000,
        color: Color(0xFFFF61B8),
      ),
      GlowBlob(
        center: Offset(167.96, 83.46),
        radii: Size(134.79, 65.37),
        rotation: -0.0009,
        softness: 0.3400,
        alpha: 1.0000,
        color: Color(0xFF000000),
      ),
      GlowBlob(
        center: Offset(559.24, -441.84),
        radii: Size(615.15, 483.09),
        rotation: 0.4128,
        softness: 0.0550,
        alpha: 0.4905,
        color: Color(0xFFFF58AC),
      ),
      GlowBlob(
        center: Offset(-709.93, 503.82),
        radii: Size(1096.63, 53.93),
        rotation: -0.5359,
        softness: 0.1401,
        alpha: 0.2136,
        color: Color(0xFF2D0C1C),
      ),
      GlowBlob(
        center: Offset(401.55, 111.21),
        radii: Size(1096.63, 8.60),
        rotation: 1.5548,
        softness: 7.3891,
        alpha: 0.1428,
        color: Color(0xFFFF71CC),
      ),
    ],
  );

  /// Medium/12.png (348×164), fit rms 1.37.
  static const m12 = GlowRecipe(
    size: Size(348, 164),
    base: Color(0xFF000000),
    blobs: [
      GlowBlob(
        center: Offset(19.25, 194.13),
        radii: Size(1096.63, 15.67),
        rotation: 0.9636,
        softness: 2.4501,
        alpha: 0.9206,
        color: Color(0xFF315E1F),
      ),
      GlowBlob(
        center: Offset(-425.38, 168.95),
        radii: Size(1096.63, 23.79),
        rotation: 0.0127,
        softness: 0.5997,
        alpha: 0.2872,
        color: Color(0xFFA2FF66),
      ),
      GlowBlob(
        center: Offset(-313.92, 60.70),
        radii: Size(1096.63, 42.21),
        rotation: -0.2041,
        softness: 0.4173,
        alpha: 0.2179,
        color: Color(0xFF27FF1B),
      ),
      GlowBlob(
        center: Offset(360.92, 683.99),
        radii: Size(1096.63, 444.79),
        rotation: 2.3593,
        softness: 0.0488,
        alpha: 0.2144,
        color: Color(0xFF8EFF5A),
      ),
      GlowBlob(
        center: Offset(326.91, 4.54),
        radii: Size(1096.63, 30.68),
        rotation: 0.3307,
        softness: 0.6107,
        alpha: 0.2078,
        color: Color(0xFF2EFF20),
      ),
    ],
  );

  /// Medium/14.png (348×164), fit rms 0.98.
  static const m14 = GlowRecipe(
    size: Size(348, 164),
    base: Color(0xFF000000),
    blobs: [
      GlowBlob(
        center: Offset(1134.51, -194.47),
        radii: Size(1096.63, 87.36),
        rotation: -0.4221,
        softness: 0.1688,
        alpha: 1.0000,
        color: Color(0xFFABFE00),
      ),
      GlowBlob(
        center: Offset(-800.83, 202.63),
        radii: Size(1096.63, 60.83),
        rotation: -0.0172,
        softness: 0.1297,
        alpha: 0.5646,
        color: Color(0xFF6FAC17),
      ),
      GlowBlob(
        center: Offset(466.11, -986.37),
        radii: Size(1096.63, 149.67),
        rotation: -1.4796,
        softness: 0.0779,
        alpha: 0.4353,
        color: Color(0xFF86FFA6),
      ),
      GlowBlob(
        center: Offset(795.98, -195.22),
        radii: Size(1096.63, 25.53),
        rotation: -0.5301,
        softness: 0.3606,
        alpha: 0.1027,
        color: Color(0xFFA4FF23),
      ),
      GlowBlob(
        center: Offset(169.40, 146.80),
        radii: Size(72.46, 18.11),
        rotation: -0.1640,
        softness: 0.3214,
        alpha: 0.1595,
        color: Color(0xFF5F9820),
      ),
      GlowBlob(
        center: Offset(326.66, 118.65),
        radii: Size(91.11, 38.23),
        rotation: -0.3642,
        softness: 0.4460,
        alpha: 0.4829,
        color: Color(0xFF1E3E35),
      ),
    ],
  );

  /// Medium/16.png (348×164), fit rms 0.71.
  static const m16 = GlowRecipe(
    size: Size(348, 164),
    base: Color(0xFF300808),
    blobs: [
      GlowBlob(
        center: Offset(-98.21, -33.54),
        radii: Size(1096.63, 77.79),
        rotation: 0.0305,
        softness: 0.5415,
        alpha: 1.0000,
        color: Color(0xFFFF4A4A),
      ),
      GlowBlob(
        center: Offset(31.39, 112.00),
        radii: Size(113.82, 52.52),
        rotation: 2.3623,
        softness: 0.2979,
        alpha: 0.0249,
        color: Color(0xFFFF6565),
      ),
      GlowBlob(
        center: Offset(178.22, 85.32),
        radii: Size(162.48, 38.29),
        rotation: 0.0058,
        softness: 0.4496,
        alpha: 1.0000,
        color: Color(0xFF000101),
      ),
      GlowBlob(
        center: Offset(183.74, 44.61),
        radii: Size(238.28, 44.13),
        rotation: 0.0142,
        softness: 0.4259,
        alpha: 0.5275,
        color: Color(0xFF000000),
      ),
      GlowBlob(
        center: Offset(328.17, 119.36),
        radii: Size(84.88, 60.12),
        rotation: 3.7265,
        softness: 0.2248,
        alpha: 0.0207,
        color: Color(0xFFFF5252),
      ),
    ],
  );

  /// Medium/20.png (348×164), fit rms 0.47.
  static const m20 = GlowRecipe(
    size: Size(348, 164),
    base: Color(0xFF127A7F),
    blobs: [
      GlowBlob(
        center: Offset(50.28, 0.90),
        radii: Size(1096.63, 7.20),
        rotation: -0.0041,
        softness: 7.3891,
        alpha: 1.0000,
        color: Color(0xFF3DFFD9),
      ),
      GlowBlob(
        center: Offset(313.64, 169.75),
        radii: Size(1096.63, 6.92),
        rotation: 0.0300,
        softness: 7.3891,
        alpha: 1.0000,
        color: Color(0xFF008ABB),
      ),
      GlowBlob(
        center: Offset(172.91, 81.19),
        radii: Size(206.62, 56.68),
        rotation: 0.0036,
        softness: 0.6269,
        alpha: 1.0000,
        color: Color(0xFF000000),
      ),
      GlowBlob(
        center: Offset(692.14, 0.22),
        radii: Size(1096.63, 3.01),
        rotation: -0.3646,
        softness: 7.3891,
        alpha: 0.0359,
        color: Color(0xFF008CFF),
      ),
      GlowBlob(
        center: Offset(-809.44, 40.29),
        radii: Size(1096.63, 42.52),
        rotation: -0.0054,
        softness: 0.1025,
        alpha: 0.0122,
        color: Color(0xFF30FFFE),
      ),
      GlowBlob(
        center: Offset(174.71, 82.38),
        radii: Size(89.22, 21.63),
        rotation: 0.0014,
        softness: 0.4908,
        alpha: 1.0000,
        color: Color(0xFF000000),
      ),
    ],
  );

  /// Large/1.png (348×365), fit rms 1.09.
  static const l1 = GlowRecipe(
    size: Size(348, 365),
    base: Color(0xFF005A97),
    blobs: [
      GlowBlob(
        center: Offset(313.23, 493.95),
        radii: Size(1096.63, 276.49),
        rotation: -3.0976,
        softness: 0.5573,
        alpha: 1.0000,
        color: Color(0xFFFFB486),
      ),
      GlowBlob(
        center: Offset(174.67, 175.18),
        radii: Size(82.39, 95.66),
        rotation: -0.0021,
        softness: 0.4157,
        alpha: 1.0000,
        color: Color(0xFF080000),
      ),
      GlowBlob(
        center: Offset(173.89, 194.97),
        radii: Size(230.72, 237.60),
        rotation: -0.2004,
        softness: 0.5913,
        alpha: 1.0000,
        color: Color(0xFF000000),
      ),
      GlowBlob(
        center: Offset(525.05, 1284.27),
        radii: Size(194.13, 1096.63),
        rotation: -0.4895,
        softness: 0.0158,
        alpha: 0.0050,
        color: Color(0xFFFF9B3E),
      ),
      GlowBlob(
        center: Offset(671.56, 15.95),
        radii: Size(580.06, 363.87),
        rotation: 1.0269,
        softness: 0.0720,
        alpha: 0.0239,
        color: Color(0xFF7DDFFF),
      ),
      GlowBlob(
        center: Offset(-658.41, 915.38),
        radii: Size(70.99, 1096.63),
        rotation: 0.6430,
        softness: 0.2465,
        alpha: 0.0441,
        color: Color(0xFF41CBFF),
      ),
    ],
  );

  /// Large/5.png (348×365), fit rms 0.56.
  static const l5 = GlowRecipe(
    size: Size(348, 365),
    base: Color(0xFF0EA25D),
    blobs: [
      GlowBlob(
        center: Offset(174.85, 336.75),
        radii: Size(207.54, 493.18),
        rotation: -0.0019,
        softness: 0.3858,
        alpha: 0.9646,
        color: Color(0xFF0B0D0A),
      ),
      GlowBlob(
        center: Offset(332.26, 532.87),
        radii: Size(73.37, 261.00),
        rotation: 0.3762,
        softness: 1.6337,
        alpha: 1.0000,
        color: Color(0xFFC1002F),
      ),
      GlowBlob(
        center: Offset(34.27, 655.61),
        radii: Size(112.02, 431.98),
        rotation: -0.3580,
        softness: 1.0066,
        alpha: 1.0000,
        color: Color(0xFFBC002E),
      ),
      GlowBlob(
        center: Offset(629.89, -583.29),
        radii: Size(1096.63, 139.12),
        rotation: -1.0389,
        softness: 0.0244,
        alpha: 0.0104,
        color: Color(0xFF006036),
      ),
      GlowBlob(
        center: Offset(174.21, 174.32),
        radii: Size(39.48, 76.12),
        rotation: 0.0106,
        softness: 0.9457,
        alpha: 1.0000,
        color: Color(0xFF000000),
      ),
      GlowBlob(
        center: Offset(3120.51, 194.43),
        radii: Size(40.24, 1096.63),
        rotation: 1.6053,
        softness: 0.9177,
        alpha: 1.0000,
        color: Color(0xFF59252B),
      ),
    ],
  );

  /// Large/6.png (348×365), fit rms 0.31.
  static const l6 = GlowRecipe(
    size: Size(348, 365),
    base: Color(0xFF400B0B),
    blobs: [
      GlowBlob(
        center: Offset(171.94, 42.90),
        radii: Size(155.73, 148.88),
        rotation: 10.7799,
        softness: 0.5704,
        alpha: 1.0000,
        color: Color(0xFF000000),
      ),
      GlowBlob(
        center: Offset(-4027.52, -60.55),
        radii: Size(1096.63, 14.42),
        rotation: -0.0069,
        softness: 7.3891,
        alpha: 0.8244,
        color: Color(0xFFFF2C2C),
      ),
      GlowBlob(
        center: Offset(207.68, 1335.88),
        radii: Size(440.50, 1096.63),
        rotation: -0.0407,
        softness: 0.0883,
        alpha: 1.0000,
        color: Color(0xFF2C0707),
      ),
      GlowBlob(
        center: Offset(158.18, 123.37),
        radii: Size(46.18, 110.90),
        rotation: -0.5295,
        softness: 0.1978,
        alpha: 0.0099,
        color: Color(0xFF000101),
      ),
      GlowBlob(
        center: Offset(198.00, 202.51),
        radii: Size(136.72, 60.03),
        rotation: -1.0883,
        softness: 0.1069,
        alpha: 0.0220,
        color: Color(0xFF270C0C),
      ),
      GlowBlob(
        center: Offset(175.94, 89.93),
        radii: Size(31.78, 19.66),
        rotation: 3.1372,
        softness: 1.4438,
        alpha: 1.0000,
        color: Color(0xFF000000),
      ),
    ],
  );

  /// Large/7.png (348×365), fit rms 0.39.
  static const l7 = GlowRecipe(
    size: Size(348, 365),
    base: Color(0xFF000308),
    blobs: [
      GlowBlob(
        center: Offset(9.78, -55.76),
        radii: Size(71.79, 1096.63),
        rotation: 0.3762,
        softness: 0.4657,
        alpha: 1.0000,
        color: Color(0xFFFFA117),
      ),
      GlowBlob(
        center: Offset(53.12, 1332.55),
        radii: Size(62.64, 1096.63),
        rotation: -0.0778,
        softness: 0.1512,
        alpha: 1.0000,
        color: Color(0xFF5F490E),
      ),
      GlowBlob(
        center: Offset(228.43, -18.62),
        radii: Size(1096.63, 65.35),
        rotation: -0.3350,
        softness: 0.5165,
        alpha: 1.0000,
        color: Color(0xFFFF7E1A),
      ),
      GlowBlob(
        center: Offset(359.79, 363.20),
        radii: Size(298.18, 390.68),
        rotation: -0.7466,
        softness: 0.0164,
        alpha: 1.0000,
        color: Color(0xFF0A0A0A),
      ),
      GlowBlob(
        center: Offset(719.00, -204.39),
        radii: Size(1096.63, 120.66),
        rotation: -0.2110,
        softness: 0.1458,
        alpha: 0.1690,
        color: Color(0xFFFF0037),
      ),
      GlowBlob(
        center: Offset(206.40, 86.32),
        radii: Size(121.40, 214.41),
        rotation: 1.2583,
        softness: 0.3529,
        alpha: 1.0000,
        color: Color(0xFF0A0A0A),
      ),
    ],
  );

  /// Large/8.png (348×365), fit rms 0.30.
  static const l8 = GlowRecipe(
    size: Size(348, 365),
    base: Color(0xFF283B00),
    blobs: [
      GlowBlob(
        center: Offset(224.93, -1132.33),
        radii: Size(56.70, 468.05),
        rotation: -0.2733,
        softness: 3.0481,
        alpha: 1.0000,
        color: Color(0xFF8AFF94),
      ),
      GlowBlob(
        center: Offset(464.37, -236.07),
        radii: Size(41.63, 150.50),
        rotation: 1.4279,
        softness: 7.3891,
        alpha: 1.0000,
        color: Color(0xFF53D0FF),
      ),
      GlowBlob(
        center: Offset(-312.16, 839.54),
        radii: Size(15.81, 1096.63),
        rotation: 1.0027,
        softness: 7.3891,
        alpha: 1.0000,
        color: Color(0xFF3D5A00),
      ),
      GlowBlob(
        center: Offset(37.41, 320.02),
        radii: Size(82.41, 97.39),
        rotation: -0.9165,
        softness: 0.6772,
        alpha: 1.0000,
        color: Color(0xFF000000),
      ),
      GlowBlob(
        center: Offset(50.03, 319.01),
        radii: Size(58.12, 100.81),
        rotation: -0.8138,
        softness: 0.2440,
        alpha: 1.0000,
        color: Color(0xFF000002),
      ),
      GlowBlob(
        center: Offset(-20.29, 471.70),
        radii: Size(294.48, 384.32),
        rotation: 0.0180,
        softness: 0.4501,
        alpha: 1.0000,
        color: Color(0xFF000000),
      ),
    ],
  );
}
