// The home-screen widgets paint the same glow recipes, inks and type as the
// tiles, from a JSON file the Kotlin renderer reads
// (res/raw/airlog_widget_glows.json). This test keeps that file equal to
// GlowRecipes, PlanTile.glowFor, TileInk, C, P and F, so none of them is
// retyped by hand in Kotlin (docs/WIDGETS_PLAN.md §1).
//
// Regenerate: AIRLOG_WRITE_WIDGET_GLOWS=1 flutter test -j 1
//   test/data/widget_glows_test.dart

import 'dart:convert';
import 'dart:io';

import 'package:airlog/design/design.dart';
import 'package:airlog/domain/today_plan.dart';
import 'package:flutter/painting.dart';
import 'package:flutter_test/flutter_test.dart';

const _path = 'android/app/src/main/res/raw/airlog_widget_glows.json';

/// Which recipe each widget paints. Recovery = RingScoreTile (Small/5);
/// Today = Medium/19; the plan follows PlanTile.glowFor(state).
final _widgets = <String, GlowRecipe>{
  'recovery': GlowRecipes.s5,
  'today': GlowRecipes.m19,
};

String _name(GlowRecipe r) {
  const all = {
    's2': GlowRecipes.s2,
    's5': GlowRecipes.s5,
    's6': GlowRecipes.s6,
    's7': GlowRecipes.s7,
    's8': GlowRecipes.s8,
    's9': GlowRecipes.s9,
    's17': GlowRecipes.s17,
    'm5': GlowRecipes.m5,
    'm7': GlowRecipes.m7,
    'm8': GlowRecipes.m8,
    'm10': GlowRecipes.m10,
    'm12': GlowRecipes.m12,
    'm14': GlowRecipes.m14,
    'm16': GlowRecipes.m16,
    'm19': GlowRecipes.m19,
    'm20': GlowRecipes.m20,
    'l1': GlowRecipes.l1,
    'l5': GlowRecipes.l5,
    'l6': GlowRecipes.l6,
    'l7': GlowRecipes.l7,
    'l8': GlowRecipes.l8,
  };
  return all.entries.firstWhere((e) => identical(e.value, r)).key;
}

int _argb(Color c) => c.toARGB32();

Map<String, Object> _recipe(GlowRecipe r) => {
  'w': r.size.width,
  'h': r.size.height,
  'base': _argb(r.base),
  'blobs': [
    for (final b in r.blobs)
      () {
        final (colors, stops) = b.profile();
        return {
          'cx': b.center.dx,
          'cy': b.center.dy,
          'rx': b.radii.width,
          'ry': b.radii.height,
          'rot': b.rotation,
          'reach': b.reach,
          'colors': [for (final c in colors) _argb(c)],
          'stops': stops,
        };
      }(),
  ],
};

/// Ink and type the Kotlin renderer uses, read from the design tokens.
Map<String, int> _ink() => {
  'primary': _argb(TileInk.primary),
  'unit': _argb(TileInk.unit),
  'unitSoft': _argb(TileInk.unitSoft),
  'secondary': _argb(TileInk.secondary),
  'tertiary': _argb(TileInk.tertiary),
  'ring': _argb(C.ring),
  'plate': _argb(C.badge),
  'lime': _argb(C.lime),
  'chipBg': _argb(const P().wash(C.amber)),
  'chipInk': _argb(const P().on(C.amber)),
};

Map<String, Object?> _type(TextStyle t) => {
  'family': t.fontFamily,
  'size': t.fontSize,
  'weight': (t.fontWeight ?? FontWeight.w400).value,
  'tracking': t.letterSpacing ?? 0,
  'opsz': t.fontVariations
      ?.where((v) => v.axis == 'opsz')
      .map((v) => v.value)
      .firstOrNull,
};

Map<String, Object?> _types() => {
  'tileHeadline': _type(F.tileHeadline),
  'tileTitle': _type(F.tileTitle),
  'tileBody': _type(F.tileBody),
  'tileLabel': _type(F.tileLabel),
  'tileMicro': _type(F.tileMicro),
  'micro': _type(F.micro.copyWith(fontWeight: FontWeight.w600)),
  'dot32': _type(F.dot32),
  'dot40': _type(F.dot40),
};

String generate() {
  final plan = {
    for (final s in DayState.values) s.name: _name(PlanTile.glowFor(s)),
  };
  final byName = <String, GlowRecipe>{
    for (final r in [
      ..._widgets.values,
      for (final s in DayState.values) PlanTile.glowFor(s),
    ])
      _name(r): r,
  };
  final names = byName.keys.toList()..sort();
  final out = {
    '_': 'GENERATED by test/data/widget_glows_test.dart from GlowRecipes, '
        'TileInk, C, P and F. '
        'Do not edit by hand.',
    'widgets': {for (final e in _widgets.entries) e.key: _name(e.value)},
    'plan': plan,
    'ink': _ink(),
    'type': _types(),
    'recipes': {for (final n in names) n: _recipe(byName[n]!)},
  };
  return '${const JsonEncoder.withIndent(' ').convert(out)}\n';
}

void main() {
  test('res/raw/airlog_widget_glows.json matches GlowRecipes', () {
    final want = generate();
    final f = File(_path);
    if (Platform.environment['AIRLOG_WRITE_WIDGET_GLOWS'] == '1') {
      f.parent.createSync(recursive: true);
      f.writeAsStringSync(want);
    }
    expect(
      f.existsSync() ? f.readAsStringSync().replaceAll('\r\n', '\n') : '',
      want,
      reason:
          'The widget glow file is out of date. Run '
          'AIRLOG_WRITE_WIDGET_GLOWS=1 flutter test -j 1 '
          'test/data/widget_glows_test.dart',
    );
  });
}
