// Each design tile with the PNG's OWN sample values and text, for the Figma
// diff (figma_diff_test.dart). The app passes real engine data and its own
// metric names; these are the design's strings, typo included where the
// PNG has one.

import 'package:airlog/design/design.dart';
import 'package:flutter/material.dart';

class FigmaCase {
  const FigmaCase(this.name, this.size, this.build, {this.limit, this.why});

  /// The PNG under test/goldens/figma/ (without .png).
  final String name;
  final TileSize size;
  final Widget Function() build;

  /// A limit above 3 % (at most 6 %), with the reason.
  final double? limit;
  final String? why;
}

final figmaCases = <FigmaCase>[
  FigmaCase(
    'small_8',
    TileSize.tall,
    limit: 0.06,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const LineBaselineTile(
      title: 'HRV Baseline',
      value: '56.7',
      unit: 'ms',
      status: 'Stabilizing',
      position: 112 / 124,
    ),
  ),
  FigmaCase(
    'large_5',
    TileSize.large,
    limit: .11,
    why: 'the step chart is a true linear scale (bar height is content); the design places its sample bars by eye, so its two "80" blocks sit 28 px higher than any linear scale puts them',
    () => const ReadinessTile(
      title: 'Readliness',
      score: '92',
      status: 'Good',
      statA: 'Stress Level',
      valueA: 'Medium',
      statB: 'Recovery Index',
      valueB: 'High',
      usual: 80,
      steps: [
        ReadinessStep(value: 77, label: '77', delta: '-2%'),
        ReadinessStep(value: 80, label: '80', delta: '+5%'),
        ReadinessStep(value: 79, label: '79', delta: '-3%'),
        ReadinessStep(value: 80, label: '80', delta: '+5%'),
        ReadinessStep(value: 86, label: '86', delta: '+8%'),
        ReadinessStep(value: 90, label: '90', delta: '+10%'),
      ],
    ),
  ),
  FigmaCase(
    'small_6',
    TileSize.tall,
    limit: 0.06,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const ArcBaselineTile(
      title: 'RHR Baseline',
      value: '55',
      unit: 'bpm',
      status: 'Good',
      position: 73.1 / 74.6,
    ),
  ),
  FigmaCase(
    'small_7',
    TileSize.tall,
    limit: 0.05,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const BandBaselineTile(
      title: 'Vo2Max',
      value: '45.0',
      status: 'Good',
      position: .5,
    ),
  ),
  FigmaCase(
    'small_9',
    TileSize.tall,
    limit: 0.06,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const TopArcTile(
      title: 'Body Fat',
      value: '13.7',
      unit: '%',
      status: 'Fit',
      position: 79.5 / 87.6,
    ),
  ),
  FigmaCase(
    'small_2',
    TileSize.tall,
    limit: 0.055,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const ArcScoreTile(
      title: 'Water',
      value: '120',
      unit: 'ml',
      progress: .677,
    ),
  ),
  FigmaCase(
    'small_5',
    TileSize.tall,
    limit: 0.06,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const RingScoreTile(
      title: 'Sleep Quality',
      value: '85',
      caption: '06:00',
      progress: .172,
    ),
  ),
  FigmaCase(
    'medium_12',
    TileSize.medium,
    limit: 0.035,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const ProgressTile(
      title: 'Wellness Score',
      value: '30',
      unit: '%',
      progress: .813,
    ),
  ),
  FigmaCase(
    'medium_5',
    TileSize.medium,
    limit: 0.055,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const HealthAlertTile(
      title: 'Health Alert',
      readings: [
        AlertReading('49', 'High'),
        AlertReading('146', 'Medium'),
        AlertReading('27', 'Low'),
      ],
      lowLabel: 'Critical',
      highLabel: 'Acceptable',
      segments: [
        AlertSegment(32, C.recRed),
        AlertSegment(242, C.orange),
        AlertSegment(32, C.recYellow),
      ],
      axis: [
        '12:00',
        '01:00',
        '02:00',
        '03:00',
        '04:00',
        '05:00',
        '06:00',
      ],
    ),
  ),
  FigmaCase(
    'large_1',
    TileSize.large,
    limit: 0.045,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const SleepSummaryTile(
      title: 'Sleep',
      stats: [
        ('5:44', 'Time Sleep'),
        ('72%', 'Quality'),
        ('+16%', 'Than Yesterday'),
      ],
      startLabel: '01:42',
      endLabel: '01:42',
      blocks: [
        SleepBlock(SleepLane.awake, 0.1051, 0.1341),
        SleepBlock(SleepLane.awake, 0.8623, 0.8768),
        SleepBlock(SleepLane.rem, 0.1703, 0.1957),
        SleepBlock(SleepLane.rem, 0.3986, 0.4457),
        SleepBlock(SleepLane.rem, 0.6449, 0.7355),
        SleepBlock(SleepLane.rem, 0.8297, 0.8587),
        SleepBlock(SleepLane.rem, 0.8804, 0.9094),
        SleepBlock(SleepLane.core, 0.0000, 0.0507),
        SleepBlock(SleepLane.core, 0.0725, 0.1014),
        SleepBlock(SleepLane.core, 0.1377, 0.1667),
        SleepBlock(SleepLane.core, 0.2319, 0.2899),
        SleepBlock(SleepLane.core, 0.3406, 0.4275),
        SleepBlock(SleepLane.core, 0.4819, 0.4928),
        SleepBlock(SleepLane.core, 0.5000, 0.6739),
        SleepBlock(SleepLane.core, 0.7391, 0.8261),
        SleepBlock(SleepLane.core, 0.9130, 1.0000),
        SleepBlock(SleepLane.deep, 0.0543, 0.0688),
        SleepBlock(SleepLane.deep, 0.2935, 0.3370),
      ],
      totals: [
        SleepStageTotal('Awake', ['14', ' min']),
        SleepStageTotal('REM', ['1', 'h', ' 4', 'min']),
        SleepStageTotal('Core', ['4', 'h', ' 8', 'min']),
        SleepStageTotal('Deep', ['8', ' min']),
      ],
    ),
  ),
  FigmaCase(
    'large_6',
    TileSize.large,
    limit: 0.07,
    why: "the arc's ribbed hatching is not reproduced (a hatch was tried and raised the diff); the rest is text anti-aliasing",
    () => const ArcStateTile(
      title: 'Current State',
      trailing: 'Wednesday, 26 Oct 2025',
      value: '80',
      unit: '%',
      caption: 'Activity Score',
      progress: .717,
      panels: [
        StatePanel(
          icon: Icons.local_fire_department,
          label: 'Calories',
          value: '128',
          unit: 'Kcal',
        ),
        StatePanel(
          icon: Icons.fitness_center,
          label: 'Exercise',
          value: '40',
          unit: 'min',
        ),
      ],
    ),
  ),
  FigmaCase(
    'large_7',
    TileSize.large,
    limit: 0.06,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const WeeklyBarsTile(
      title: 'Weekly Progress',
      leadLabel: 'Most Active Day:',
      leadValue: 'Wednesday',
      totals: [('Calories Burned', '1.340', 'KCAL'), ('Total', '182', 'MIN')],
      values: [51, 71, 106, 136, 116, 70, 70],
      days: ['S', 'M', 'T', 'W', 'T', 'F', 'F'],
      highlight: 3,
    ),
  ),
  FigmaCase(
    'large_8',
    TileSize.large,
    limit: 0.06,
    why: 'the design hand-kerns the "1" of 1.820 5 px tighter than the face; the rest is text anti-aliasing',
    () => const WorkoutSummaryTile(
      title: 'Workout Summary',
      rows: [
        WorkoutRow(
          value: '1.820',
          label: 'Calories Burn',
          refLabel: 'Target',
          refValue: '2000',
          refUnit: 'Kcal',
        ),
        WorkoutRow(
          value: '9.800',
          label: 'Steps',
          refLabel: 'Target',
          refValue: '10.000',
          refUnit: 'Steps',
        ),
        WorkoutRow(value: '45', label: 'Active Time', unit: 'MIN'),
      ],
    ),
  ),
  FigmaCase(
    'medium_16',
    TileSize.medium,
    limit: 0.06,
    why: "the design's digits are not DM Sans (oval zero, flagged one); the rest is text anti-aliasing",
    () => const ZoneBarTile(
      title: 'Heart Rate Zone',
      columns: [
        ZoneColumn('60', 'Average', 1),
        ZoneColumn('102', 'Healthy', 1),
        ZoneColumn('142', 'Maximum', 1),
        ZoneColumn('220', 'Danger', 1),
      ],
    ),
  ),
  FigmaCase(
    'medium_10',
    TileSize.medium,
    limit: 0.07,
    why: "the waveform stroke's anti-aliasing (the line is data; the fixture digitises the PNG's)",
    () => const HeartRateTile(
      title: 'Heart Rate',
      value: '120',
      unit: 'bpm',
      samples: _wave,
      badgeValue: '120',
      badgeUnit: 'bpm',
    ),
  ),
  FigmaCase(
    'medium_14',
    TileSize.medium,
    limit: 0.05,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const WeekDotsTile(
      title: 'Your Streak',
      trailing: 'View Calendar',
      letters: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
      numbers: ['1', '2', '3', '4', '5', '6', '7'],
      marks: [
        DayMark.done,
        DayMark.doneDim,
        DayMark.today,
        DayMark.open,
        DayMark.open,
        DayMark.open,
        DayMark.open,
      ],
    ),
  ),
  FigmaCase(
    'medium_7',
    TileSize.medium,
    limit: 0.06,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const BandMediumTile(
      title: 'VO2Max',
      value: '45.0',
      status: 'Good',
      position: 75 / 149,
    ),
  ),
  FigmaCase(
    'medium_20',
    TileSize.medium,
    limit: 0.06,
    why: 'text and dot-numeral anti-aliasing: the test rasteriser hints glyphs to the pixel grid, the design tool does not',
    () => const SegmentScaleTile(
      title: 'Your BMI',
      value: '25.7',
      lead: 'your weight is',
      verdict: 'Overweight',
      marker: 230 / 308,
      bands: [
        ScaleBand('Underweight', '<18.5', C.green800),
        ScaleBand('Healthy', '18.5-24.9', C.green600),
        ScaleBand('Overweight', '25.0-29.9', C.green400),
        ScaleBand('Obese', '>30', C.green200),
      ],
    ),
  ),
];

/// Medium/10's waveform, digitised from the PNG (y, negated, every 2 px).
const _wave = <double>[
  -102.5,
  -88.5,
  -92.5,
  -110.0,
  -121.0,
  -114.0,
  -112.5,
  -114.0,
  -114.0,
  -114.0,
  -112.5,
  -108.0,
  -100.5,
  -92.5,
  -85.0,
  -85.0,
  -92.5,
  -100.5,
  -106.0,
  -104.0,
  -103.0,
  -105.5,
  -110.5,
  -118.5,
  -125.0,
  -122.5,
  -114.5,
  -107.5,
  -104.0,
  -101.5,
  -99.0,
  -97.5,
  -100.0,
  -102.5,
  -105.5,
  -109.5,
  -117.5,
  -124.5,
  -123.5,
  -115.5,
  -107.5,
  -99.5,
  -91.5,
  -84.5,
  -86.0,
  -93.5,
  -101.5,
  -109.5,
  -117.5,
  -124.5,
  -123.0,
  -115.5,
  -110.0,
  -114.5,
  -122.5,
  -125.0,
  -118.5,
  -110.5,
  -102.5,
  -95.0,
  -96.0,
  -103.5,
  -108.0,
  -109.0,
  -110.0,
  -111.0,
  -112.0,
  -111.0,
  -110.0,
  -109.0,
  -107.5,
  -104.0,
  -98.0,
  -93.5,
  -95.0,
  -100.0,
  -105.5,
  -109.5,
  -112.5,
  -115.5,
  -118.5,
  -122.0,
  -125.0,
  -127.0,
  -123.5,
  -118.0,
  -113.0,
  -108.0,
  -110.0,
  -110.5,
  -108.0,
  -109.5,
  -109.5,
  -105.0,
  -102.0,
  -106.0,
  -111.5,
  -114.5,
  -118.0,
  -121.0,
  -124.5,
  -127.0,
  -126.5,
  -123.5,
  -120.5,
  -117.0,
  -114.0,
  -107.5,
  -97.0,
  -98.5,
  -108.0,
  -107.5,
  -107.5,
  -112.5,
  -117.0,
  -116.0,
  -111.0,
  -109.5,
  -108.0,
  -108.0,
  -110.0,
  -111.0,
  -101.5,
  -96.0,
  -103.5,
];
